### ISSUE TITLE
First time opening

### ISSUE THREAD

**Issue by danailkh** [webzlodimir/vue-bottom-sheet#16]
It seems that for the first time, instead of going up, only the opacity changes

**Comment by Herbata-Sys** [comment]
Same here. It literally destroys first user experience.

**Comment by kidaww** [comment]
It's tiny mistake in component. Copy vue component to your project or make fork and replace
`: `-${this.cardH + this.stripe}px`; `
with
`: -(this.cardH + this.stripe);` in **init** method

**Comment by kidaww** [comment]
#17
