### ISSUE TITLE
Событие закрытия

### ISSUE THREAD

**Issue by e-zavarzin** [webzlodimir/vue-bottom-sheet#4]
Привет!
Спасибо вам за прекрасный компонент!
Есть одна сложность с его использованием, нет возможности следить за закрытием модального окна (будь то свайп или клик вне окна).
Как вариант, можно повесить event, что-нибудь вроде @closed="method"

**Comment by webzlodimir** [comment]
@e-zavarzin добрый день. В версии 1.1.7 добавлены события opened и closed.

**Comment by webzlodimir** [comment]
@e-zavarzin отпишитесь о работоспособности как попробуете, если вам не сложно.
