### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by autorunman22** [webzlodimir/vue-bottom-sheet#42]
```
<script setup>
import VueBottomSheet from "@webzlodimir/vue-bottom-sheet"
```

This triggers on Nuxt 3 after installation
<img width="1177" alt="image" src="https://github.com/vaban-ru/vue-bottom-sheet/assets/4214419/0676f085-7186-4729-ae7d-e34619920754">

**Comment by vaban-ru** [comment]
> ```
> <script setup>
> import VueBottomSheet from "@webzlodimir/vue-bottom-sheet"
> ```
> 
> This triggers on Nuxt 3 after installation <img alt="image" width="1177" src="https://user-images.githubusercontent.com/4214419/264208010-0676f085-7186-4729-ae7d-e34619920754.png">

Hey! Do you wrap vue-bottom-sheet component in `<client-only>` tag? I wrote about it in the README

**Comment by autorunman22** [comment]
@vaban-ru no usage yet just this one line import causes it.

**Comment by vaban-ru** [comment]
> @vaban-ru no usage yet just this one line import causes it.

This is client only plugin, just use `<client-only>` tag in your template like this, and there is no errors

```
<template>
  <client-only>
    <vue-bottom-sheet
        ref="myBottomSheet"
    >
      <div class="sheet-content">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime neque sed tempore ullam.
          Accusamus animi at autem beatae est, hic inventore iste minima, non quibusdam quisquam
          quos velit veritatis voluptatem?
        </p>
        <button type="button" class="btn btn-danger" @click="close">Close</button>
      </div>
    </vue-bottom-sheet>
  </client-only>
</template>
```

**Comment by autorunman22** [comment]
is there any other steps apart from installing it in order for it to work with nuxt 3? cos i literally just paste the import statement with empty div template and it wouldn't work.  if i comment the import the issue dissapears

**Comment by vaban-ru** [comment]
> is there any other steps apart from installing it in order for it to work with nuxt 3? cos i literally just paste the import statement with empty div template and it wouldn't work. if i comment the import the issue dissapears

Just importing is not enough for the plugin to work, you definitely need to place the plugin in the template

**Comment by autorunman22** [comment]
@vaban-ru 

```
<script setup>
import VueBottomSheet from "@webzlodimir/vue-bottom-sheet";
import "@webzlodimir/vue-bottom-sheet/dist/style.css";
</script>

<template lang="pug">
ClientOnly
    vue-bottom-sheet(ref="myBottomSheet")
        <h1>Lorem Ipsum</h1>
        <h2>What is Lorem Ipsum?</h2>
</template>
```

would also result to the same error. why did you have to close?

**Comment by vaban-ru** [comment]
> @vaban-ru
> 
> ```
> <script setup>
> import VueBottomSheet from "@webzlodimir/vue-bottom-sheet";
> import "@webzlodimir/vue-bottom-sheet/dist/style.css";
> </script>
> 
> <template lang="pug">
> ClientOnly
>     vue-bottom-sheet(ref="myBottomSheet")
>         <h1>Lorem Ipsum</h1>
>         <h2>What is Lorem Ipsum?</h2>
> </template>
> ```
> 
> would also result to the same error. why did you have to close?

Please paste the code I wrote below and tell me if the error will appear

```vue
<script setup lang="ts">
import VueBottomSheet from '@webzlodimir/vue-bottom-sheet'
import '@webzlodimir/vue-bottom-sheet/dist/style.css'
import {ref} from "vue";
const myBottomSheet = ref<InstanceType<typeof VueBottomSheet>>()
const open = () => {
  myBottomSheet.value?.open()
}
const close = () => {
  myBottomSheet.value?.close()
}
</script>

<template>
  <button @click="open">Open</button>
  <client-only>
    <vue-bottom-sheet
        ref="myBottomSheet"
    >
      <div class="sheet-content">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime neque sed tempore ullam.
          Accusamus animi at autem beatae est, hic inventore iste minima, non quibusdam quisquam
          quos velit veritatis voluptatem?
        </p>
        <button type="button" class="btn btn-danger" @click="close">Close</button>
      </div>
    </vue-bottom-sheet>
  </client-only>
</template>
```

**Comment by autorunman22** [comment]
@vaban-ru okay it works on a fresh page but i found out the problem - it only works without pug preprocessor. 
the problem occurs if you use `lang="pug"` you can test it yourself

**Comment by vaban-ru** [comment]
> @vaban-ru okay it works on a fresh page but i found out the problem - it only works without pug preprocessor. the problem occurs if you use `lang="pug"` you can test it yourself

Sorry, but in the near future I will not support pug preprocessor, if you want, you can send a PR with a fix for this

**Comment by vaban-ru** [comment]
And sorry for my opinion, but pug is really awful.
