### ISSUE TITLE
Dragging behaviour

### ISSUE THREAD

**Issue by topada** [webzlodimir/vue-bottom-sheet#5]
iPhone XS
iOS 14.4
Chrome OS

Expected Behaviour:
Opening the bottom sheet, I expect to be able to drag its vertical position with my finger.

Actutal Behaviour
However, I can only drag the sheet downwards. Dragging it upwards stops the dragging, probably because the dragging event is not fired outside the bottom sheet?

Possible Improvement
Fire the dragging event on the surrounding container aswell.

**Comment by abhishek97** [comment]
@webzlodimir Any update on this? I'd like to help if need be

**Comment by webzlodimir** [comment]
@abhishek97 Hello, sorry, now there is no time to solve this, you are free for PR in this issue
