### ISSUE TITLE
Vue3 support ?

### ISSUE THREAD

**Issue by ungarson** [webzlodimir/vue-bottom-sheet#7]
Does it support the Vue3?

**Comment by webzlodimir** [comment]
@ungarson Hey! I think you can try to use it in the Vue 3 project, but if it doesn't work, you are free for PR

**Comment by ungarson** [comment]
Yes, it doesn't work, sadly, so I copied the source code of the component and put it in my project as if it's my own component (not installed via npm), this way it worked.

**Comment by jonaskuske** [comment]
I'm using it like this:

```js
import VueBottomSheet from '@webzlodimir/vue-bottom-sheet/src/vue-bottom-sheet.vue'

// Vue 3 fix
VueBottomSheet.beforeUnmount = VueBottomSheet.beforeDestroy
VueBottomSheet.beforeDestroy = null
```

1) Import the `.vue` file directly (by specifying the full path), not the pre-compiled JS file
2) Rename the unmount/destroy method for Vue 3 compat

Works in Vite, not sure if Webpack or Parcel based setups support the direct `.vue` import.

**Comment by ThomasTraineau** [comment]
> Yes, it didn't work, but I managed it to work on vue 3. My solution: I copied the source code of the component and put it in my project as if it's my own component (not installed via npm), this way it worked.

Could you please share the code you used to make it work ? I can't get it to work...

**Comment by ungarson** [comment]
@ThomasTraineau go [here](https://github.com/vaban-ru/vue-bottom-sheet/blob/master/src/vue-bottom-sheet.vue), copy the code, create new component in your repository, paste the code and then use it. I can't share the code with you, because it was long time ago :)

**Comment by ThomasTraineau** [comment]
Was it the only thing to do ? Because I tried that and it didn't work



Apr 26, 2022, 22:56 by ***@***.***:

**Comment by hamonCordova** [comment]
@ungarson i tried to do this workaroud, but here i got a problem with "window is undefined" on Hammer.js (i installed it here). Do you have some sugestion?

**Comment by hamonCordova** [comment]
For those having same problem, even coping the component, adding Hammerjs to package.json dependencies and continuing with problem about "window is undefined" here is my solution. Use it on ``init()`` method.

``` 
init() {
      return new Promise(async resolve => {

        const HammerInstance = await import('hammerjs');

        this.contentH = "auto";
        this.stripe = this.isIphone() ? 20 : 0;
        this.cardH = this.$refs.bottomSheetCard.clientHeight;
        this.contentH = `${this.cardH - this.$refs.pan.clientHeight}px`;
        this.$refs.bottomSheetCard.style.maxHeight = this.maxHeight;
        this.cardP =
          this.effect === "fx-slide-from-right" ||
          this.effect === "fx-slide-from-left"
            ? 0
            : -this.cardH - this.stripe;
        if (!this.inited) {
          this.inited = true;
          let options = {
            recognizers: [
              [HammerInstance.Pan, {direction: HammerInstance.DIRECTION_VERTICAL}]
            ]
          }
          this.hammer.pan = new Hammer(this.$refs.pan, options);
          this.hammer.pan.on("panstart panup pandown panend", e => {
            this.move(e, 'pan')
          })
          this.hammer.content = new Hammer(this.$refs.bottomSheetCardContent, options);
          this.hammer.content.on("panstart panup pandown panend", e => {
            this.move(e, 'content')
          })
        }
        setTimeout(() => {
          resolve();
        }, 10);
      });
    }
